image: gitpod/workspace-full  # Use Gitpod's default image

tasks:
  - name: Start Redis
    init: |
      sudo apt update && sudo apt install -y redis-server
      redis-server --daemonize yes  # ✅ Start Redis in background
    command: redis-cli ping || echo "Redis failed to start"
