tasks:
  - name: Install Redis
    init: |
      sudo apt update && sudo apt install redis-server -y
      sudo systemctl enable redis-server
      sudo systemctl start redis-server || sudo service redis-server start
    command: redis-cli ping
